# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832a3fb14b58e17d2b2ee6e3b223aee0e6974a4b306cc6fc5743ebf4071ec87e2c173c7523b202e6774c68a615484afe4807720279edefd0d5e208200cbf1303

test:
  secret_key_base: b009f01a27e323e5e55ae39be5a4e2b7ee473d0cd32c2c6393252a3c6408279d1253297d0aa2b48acda51cd860c9f3b565d5ef45559ce87abc1503d8948cafdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
